version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      storybook:
        patterns:
          - '@storybook*'
          - 'storybook'
      svelte:
        patterns:
          - '@sveltejs*'
      semantic-release:
        patterns:
          - '@semantic-release*'
          - 'semantic-release'
      vitest:
        patterns:
          - '@vitest*'
