name: 'Build and deploy map icons'
on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./components/src/maplibre
    steps:
      - uses: actions/checkout@v4
      - run: cargo install spreet
      - run: sh ./make_sprite.sh
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      - name: 'Upload files to GCP'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './sprite'
          parent: false
          destination: 'datenhub-net-static/maps/styles/swr-datalab-light/sprite'
